Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Models/ErrorViewModel.cs
namespace RealEstates.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Controllers/DistrictsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RealEstates.Data;
using RealEstates.Models;

namespace RealEstates.Web.Controllers
{
    public class DistrictsController : Controller
    {
        private readonly RealEstateDbContext _context;

        public DistrictsController(RealEstateDbContext context)
        {
            _context = context;
        }

        // GET: Districts
        public async Task<IActionResult> Index()
        {
              return _context.Districts != null ? 
                          View(await _context.Districts.ToListAsync()) :
                          Problem("Entity set 'RealEstateDbContext.Districts'  is null.");
        }

        // GET: Districts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Districts == null)
            {
                return NotFound();
            }

            var district = await _context.Districts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (district == null)
            {
                return NotFound();
            }

            return View(district);
        }

        // GET: Districts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Districts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] District district)
        {
            if (ModelState.IsValid)
            {
                _context.Add(district);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(district);
        }

        // GET: Districts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Districts == null)
            {
                return NotFound();
            }

            var district = await _context.Districts.FindAsync(id);
            if (district == null)
            {
                return NotFound();
            }
            return View(district);
        }

        // POST: Districts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] District district)
        {
            if (id != district.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(district);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DistrictExists(district.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(district);
        }

        // GET: Districts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Districts == null)
            {
                return NotFound();
            }

            var district = await _context.Districts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (district == null)
            {
                return NotFound();
            }

            return View(district);
        }

        // POST: Districts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Districts == null)
            {
                return Problem("Entity set 'RealEstateDbContext.Districts'  is null.");
            }
            var district = await _context.Districts.FindAsync(id);
            if (district != null)
            {
                _context.Districts.Remove(district);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DistrictExists(int id)
        {
          return (_context.Districts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstates.Services;
using RealEstates.Web.Models;
using System.Diagnostics;

namespace RealEstates.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDistrictsService districtsService;

        public HomeController(IDistrictsService districtsService)
        {
            this.districtsService = districtsService;
        }
        public IActionResult Index()
        {
            var districts = this.districtsService.GetTopDistrictsByAveragePrice(133);
            return View(districts);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstates.Services;

namespace RealEstates.Web.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IPropertiesService propertiesService;

        public PropertiesController(IPropertiesService propertiesService)
        {
            this.propertiesService = propertiesService;
        }

        public ActionResult Search() 
        {
            return this.View();
        }
        public IActionResult DoSearch(int minPrice, int maxPrice)
        {
            var properties = this.propertiesService.SearchByPrice(minPrice, maxPrice);
            return this.View(properties);
        }
    }
}

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Views/Home/Index.cshtml
@model IEnumerable<RealEstates.Services.Models.DistrictViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Welcome to Real Estates BG</h1>
</div>
<table class="table table-striped table-hover table-sm">
    <tr>
        <th>District</th>
        <th>Properties</th>
        <th>Avg. price</th>
        <th>Min. price</th>
        <th>Max. price</th>
    </tr>
    @foreach (var district in this.Model.Where(p => p.PropertiesCount >= 20))
    {
        <tr>
            <td>@district.Name</td>
            <td>@district.PropertiesCount</td>
            <td>@district.AveragePrice.ToString("0.00")€</td>
            <td>@district.MinPrice€</td>
            <td>@district.MaxPrice€</td>
        </tr>
    }
</table>

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Views/Properties/DoSearch.cshtml
@model IEnumerable<RealEstates.Services.Models.PropertyViewModel>
<h1>Search results</h1>
<table class="table table-sm table-striped table-bordered table-hover">
    <tr>
        <th>District</th>
        <th>Building type</th>
        <th>Property type</th>
        <th>Price</th>
        <th>Year</th>
        <th>Size</th>
        <th>Floor</th>
    </tr>
    @foreach (var property in this.Model)
    {
        <tr>
            <td>@property.District</td>
            <td>@property.BuildingType</td>
            <td>@property.PropertyType</td>
            <td>@property.Price€</td>
            <td>
                @property.Year
                @if (property.Year.HasValue)
                {
                    @:г.
                }
            </td>
            <td>@property.Size</td>
            <td>
                @if (property.Floor != "0/0")
                {
                    @property.Floor
                }
            </td>
        </tr>
    }
</table>

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Views/Properties/Search.cshtml
<h1>Search properties by price</h1>
<form method="get" action="/Properties/DoSearch" class="col-md-6">
    <div>
    Min price: <input name="minPrice" class="form-control"/>
    </div>
    <hr />
    <div>
    Max price: <input name="maxPrice" class="form-control"/>
    </div>
    <hr />
    <input type="submit" class="btn btn-primary float-right" value="Search"/>
</form>

Best Practices And Architecture/RealEstatesProject/RealEstates.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RealEstates.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RealEstates.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RealEstates.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Search">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RealEstates.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>